# Generated by Django 4.2.1 on 2023-05-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrades',
            name='currency_pair',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usertrades',
            name='entry_point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertrades',
            name='exit_point',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
