# Generated by Django 4.2.1 on 2023-05-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_usertrades_currency_pair_usertrades_entry_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrades',
            name='trade_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
