# Generated by Django 4.2.1 on 2023-05-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_usertrades_trade_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrades',
            name='current_bal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
