# Generated by Django 4.2.1 on 2023-05-23 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_usertrades_current_bal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertrades',
            old_name='current_bal',
            new_name='new_bal',
        ),
    ]
